name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build the Docker image
      run: |
        docker build . --file ./apps/keycloak/Dockerfile \
          --tag ghcr.io/darkfella91/keycloak:latest

    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/darkfella91/keycloak:latest
