name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/keycloak/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Keycloak Version from Dockerfile
      id: extract_version
      run: |
        # Extract the version from the 'builder' line in the Dockerfile
        KEYCLOAK_VERSION=$(grep -oP '(?<=^FROM quay.io/keycloak/keycloak:)[^@]+' apps/keycloak/Dockerfile | head -n 1)
        echo "Keycloak version: $KEYCLOAK_VERSION"
        echo "KEYCLOAK_VERSION=$KEYCLOAK_VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: darkfella91/keycloak:${{ env.KEYCLOAK_VERSION }}
        platforms: linux/amd64
        build-args: |
          KEYCLOAK_VERSION=${{ env.KEYCLOAK_VERSION }}
        file: apps/keycloak/Dockerfile
        context: .
