name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Keycloak Version from Dockerfile
      id: extract_version
      run: |
        KEYCLOAK_VERSION=$(grep -oP '(?<=^FROM quay.io/keycloak/keycloak:)[\d\.]+(?:-\d+)?' Dockerfile | head -n 1) >> $GITHUB_ENV

    - name: Lowercase repository owner
      shell: bash
      run: echo "LOWERCASE_REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
            ghcr.io/${{ env.LOWERCASE_REPO }}/keycloak:latest
            ghcr.io/${{ env.LOWERCASE_REPO }}/keycloak:${{ env.KEYCLOAK_VERSION }}
        platforms: linux/amd64
        build-args: |
          KEYCLOAK_VERSION=${{ env.KEYCLOAK_VERSION }}
        file: Dockerfile
        context: .
